# Directory and file paths from config
fastq_dir: "/dfs9/ucightf-lab/projects/SmithQ/data/FASTQ"       # Directory containing FASTQ files
trimmed_dir: "output/trimmomatic"       # Directory for trimmed FASTQ files
bowtie2_dir: "output/bowtie2"       # Directory for Bowtie2 alignment outputs
macs2_dir: "output/macs2"           # Directory for MACS2 peak calling outputs
fastqc_dir: "output/fastqc_files"         # Directory for FastQC outputs
adapters: "/dfs9/ucightf-lab/kstachel/TOOLS/Trimmomatic-0.39/adapters/NexteraPE-PE.fa"             # Adapter file for Trimmomatic
bowtie2_index: "/dfs9/ucightf-lab/kstachel/TOOLS/bowtie2/GRCh38_noalt_as/GRCh38_noalt_as"   # Bowtie2 index basename
blacklist: "/dfs9/ucightf-lab/kstachel/TOOLS/blacklist/hg38-blacklist.v2.bed.gz"           # Blacklist regions file
picard_jar: "/opt/apps/picard-tools/2.27.1/picard.jar"         # Picard tools jar file
trimmomatic: "/dfs9/ucightf-lab/kstachel/TOOLS/Trimmomatic-0.39/trimmomatic-0.39.jar"   # Trimmomatic jar file
chrom_sizes: "/dfs9/ucightf-lab/kstachel/TOOLS/REFERENCES/human/hg38.chrom.sizes"  # Chromosome sizes file for hg38
bedgraph_to_bigwig: "/dfs9/ucightf-lab/kstachel/TOOLS/ucsc_tools/bedGraphToBigWig"  # bedGraphToBigWig executable